name: build images

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
    tags:
      - v*

env:
  PHP71_VERSION: 7.1
  PHP74_VERSION: 7.4

  PHP8_VERSION: 8.0

  PHP_IMAGE_NAME: 'litsoftware/php'

jobs:
  build_php_71:
    runs-on: Ubuntu-20.04
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Build PHP 7 image
        run: |
          docker build . --file ./php/7.1/cli/Dockerfile --tag $PHP_IMAGE_NAME:$PHP71_VERSION-cli
          docker build . --file ./php/7.1/fpm/Dockerfile --tag $PHP_IMAGE_NAME:$PHP71_VERSION-fpm

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} --password-stdin

      - name: Push image
        run: |
          docker push $PHP_IMAGE_NAME:$PHP71_VERSION-cli
          docker push $PHP_IMAGE_NAME:$PHP71_VERSION-fpm

  build_php_74:
    runs-on: Ubuntu-20.04
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Build PHP 7 image
        run: |
          docker build . --file ./php/7.4/cli/Dockerfile --tag $PHP_IMAGE_NAME:$PHP74_VERSION-cli
          docker build . --file ./php/7.4/fpm/Dockerfile --tag $PHP_IMAGE_NAME:$PHP74_VERSION-fpm
      
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} --password-stdin

      - name: Push image
        run: |
          docker push $PHP_IMAGE_NAME:$PHP74_VERSION-cli
          docker push $PHP_IMAGE_NAME:$PHP74_VERSION-fpm

  build_php_8:
    runs-on: Ubuntu-20.04
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2

      - name: Build PHP 8 image
        run: |
          docker build . --file ./php/8.0/cli/Dockerfile --tag $PHP_IMAGE_NAME:$PHP8_VERSION-cli
          docker build . --file ./php/8.0/fpm/Dockerfile --tag $PHP_IMAGE_NAME:$PHP8_VERSION-fpm

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_REGISTRY_USERNAME }} --password-stdin

      - name: Push image
        run: |
          docker push $PHP_IMAGE_NAME:$PHP8_VERSION-cli
          docker push $PHP_IMAGE_NAME:$PHP8_VERSION-fpm
